-- ============================================================
-- 001_get_dashboard_metrics.sql
-- BeautyOS AI
--
-- OBSOLETO / DEPRECADO
--
-- Esta receta fue la primera version del Dashboard y quedo
-- reemplazada por:
--
--   supabase/sql/008_update_dashboard_metrics.sql
--
-- No ejecutar este archivo para crear la funcion actual.
--
-- Motivo:
-- - La version antigua usaba el tenant demo "Bella Mujer".
-- - La version antigua concedia permisos a anon.
-- - La version actual usa get_my_tenant_id().
-- - La version actual solo permite authenticated.
--
-- Archivo conservado solo como referencia historica.
-- ============================================================
